### ISSUE TITLE
header-only library version

### ISSUE THREAD

**Issue by khushal-banks** [khushal-banks/log-libc#7]
checkout simple python script that generates header-only version , so it would be easy to use, because you don't need to build library and there is no need to link it to your program, e.t.c

as recommended by, @hdvpdrm on [Reddit-Post Comment](https://www.reddit.com/r/C_Programming/comments/1al8rra/comment/kq5lxkt/?utm_source=share&utm_medium=web2x&context=3)

**Comment by hdvpdrm** [comment]
i proposed idea of python script on Reddit, so i can write it. Just need some time to think about it.

**Comment by khushal-banks** [comment]
> i proposed idea of python script on Reddit, so i can write it. Just need some time to think about it.

Thank you, This is a great suggestion. I would start working on it hopefully on weekend.

**Comment by khushal-banks** [comment]
> Is there any options out there that do this already?

Hello @jgabaut. currently there is no option to do it in existing library. This was a suggestion from @hdvpdrm on [Reddit-Post](https://www.reddit.com/r/C_Programming/comments/1al8rra/a_flexible_logging_implementation_in_c/?utm_source=share&utm_medium=web2x&context=3)

This would be really helpful for me as well because link all these files in a project then adding them to the compilation process of the project is a lot of work.

**Comment by jgabaut** [comment]
@khushal-banks I was wondering, since the library is actually composed of more than one `.c` file, are all symbols in the files under `./utils/` to be included in the stb-style header?

**Comment by khushal-banks** [comment]
Right now, the ability to have seamless integration seems crucial for the library. This is not possible to do with so many files. Similar to how (issue #3 ) is planned to be solved.

Then, to solve (issue https://github.com/khushal-banks/log-libc/issues/6) sample implementation of these functions would be added in examples, which would contain existing utils function and new isolated function.

This would limit log-libc library files to
1.     README
2.     LICENSE
3.     log_print.c
4.     log_print.h
5.     log_manage.c
6.     log_manage.h
7.     an example directory with sample code utilizing all features of library,

    like example/example1/main.c example/example1/file_op.c, example/example1/time.c, example/example1/Makefile
    similarly, more in example/example2 etc

name of example1, example2 directories can be,
NTFS file-based logging, EXT4 auto-deletetion feature, colored output in terminal, Embedded Free RTOS logging

Then there would be no need to have a header-only library version.
And this library would become independent of the endless possible use-cases.

@jgabaut Do you think this issue would be still relevant?

**Comment by jgabaut** [comment]
I'm failing to grasp exactly in which way the isolation of the dependencies in `log_print.c` should be carried out. Is the implementation supposed to come in a minimal-compilable state that can be redefined? 

For example, stub implementations of the "to be defined" functions that result in a noop are provided with the library, so that the implementation can be compiled as-is anyway?

Or, a `#ifndef` preproc guard on the dependant calls inside the `log_print.c` library functions, so that they don't get compiled without defining a marker macro together with the user-implementation?

Or, rather, the would-be examples are to be used as the aforementioned stub implementations? This sounds nice and tidy but I don't know if it's doable. Sounds like enough preprocessor guards could get the magic done, but maybe _that's too much voodoo_.

**Comment by khushal-banks** [comment]
Yeah, i agree this seems unnecessary to me as well.
As, stated above after the file restructure, using this library would be easy without the need of having a header-only library version.
So, closing this issue. I will reopen this after solving issue #3 if someone else request this feature which is highly unlikely.
